const {createProxyMiddleware} = require('http-proxy-middleware');
const proxy = {
    target:"https://backend.accelerateiq.ai",
    changeOrigin:true
}
module.exports = function (app) {
    app.use(
        '/call-options',
        createProxyMiddleware(proxy)
    );
    app.use(
        '/call-options-notes',
        createProxyMiddleware(proxy)
    );
    app.use(
        '/call-contact-update',
        createProxyMiddleware(proxy)
    );
    app.use(
        '/call-options-search',
        createProxyMiddleware(proxy)
    );
    app.use(
        '/find-lead',
        createProxyMiddleware(proxy)
    );
    app.use(
        '/signin',
        createProxyMiddleware(proxy)
    );
    app.use(
        '/signup',
        createProxyMiddleware(proxy)
    );
    app.use('/db',
        createProxyMiddleware(proxy));
    app.use('/token',
        createProxyMiddleware(proxy)
    );
    app.use('/logout',
        createProxyMiddleware(proxy));
    app.use('/cdashboard',createProxyMiddleware(proxy));
    app.use('/tabs-data',createProxyMiddleware(proxy));
    app.use('/dialoutcomes',createProxyMiddleware(proxy));
    app.use('/mdashboarddata',createProxyMiddleware(proxy));
    app.use('/callerstats',createProxyMiddleware(proxy));
};
